dhd: Use find to point makeudev to uventd rcs instead of paths
mer-hybris/droid-hal-device pull request #240
Opened 2019-10-22 13:16 UTC by Thaodan

Instead of pointed makeudev to paths that maybe not exist and filter
with ls, use find and filter directly.
This also fixes cases where for example there's no /system/vendor and just
/vendor (which is enforced with later android versions).

2020-10-30 11:26 UTC, sledges requested changes

2020-10-30 11:26 UTC, sledges commented on droid-hal-device.inc
> +    -name ueventd.rc -o -name ueventd.\*.rc -a ! -name \*.goldfish.rc ) \
Please split into newlines for better readability
```suggestion
    $(find %{android_root}/out/target/product/%{device}/system \
           %{android_root}/out/target/product/%{device}/root \
           %{android_root}/out/target/product/%{device}/vendor \
           -name ueventd.rc -o -name ueventd.\*.rc -a ! -name \*.goldfish.rc ) \
```

2020-10-31 00:31 UTC, Thaodan commented
Rebased and adjusted.

2020-11-02 08:26 UTC, sledges commented on droid-hal-device.inc
> +    -name ueventd.rc -o -name ueventd.\*.rc -a ! -name \*.goldfish.rc ) \
The whole block now looks off:
```bash
%{dhd_path}/helpers/makeudev \
 $(find %{android_root}/out/target/product/%{device}/system \
        %{android_root}/out/target/product/%{device}/root \
        %{android_root}/out/target/product/%{device}/vendor \
    -name ueventd.rc -o -name ueventd.\*.rc -a ! -name \*.goldfish.rc ) \
        > tmp/udev.rules/999-android-system.rules
```
I suggest
```bash
%{dhd_path}/helpers/makeudev \
    $(find %{android_root}/out/target/product/%{device}/system \
           %{android_root}/out/target/product/%{device}/root \
           %{android_root}/out/target/product/%{device}/vendor \
          -name ueventd.rc -o -name ueventd.\*.rc -a ! -name \*.goldfish.rc ) \
    > tmp/udev.rules/999-android-system.rules
```

2020-11-09 08:56 UTC, sledges approved these changes

2020-11-09 08:57 UTC, merged