dhd: mkbootimg is mkbootimg.py in later versions
mer-hybris/droid-hal-device pull request #243
Opened 2019-10-26 16:02 UTC by Thaodan

mkbootimg is mkbootimg.py in later versions

2020-10-30 11:19 UTC, sledges requested changes

2020-10-30 11:19 UTC, sledges commented on droid-hal-device.inc
> +fi
nitpick: indent should be 4 spaces each
```suggestion
if [ -e %{android_root}/system/core/mkbootimg/mkbootimg.py ]; then
    install -m 755 -D %{android_root}/system/core/mkbootimg/mkbootimg.py \
            %{buildroot}/%{_bindir}/mkbootimg
else
    install -m 755 -D %{android_root}/system/core/mkbootimg/mkbootimg %{buildroot}/%{_bindir}/
fi
```

2020-10-30 23:02 UTC, Thaodan commented on droid-hal-device.inc
> +fi
Refactored this a bit.

2020-11-02 08:16 UTC, sledges commented on droid-hal-device.inc
> +if [ -e %{android_root}/system/core/mkbootimg/mkbootimg.py ] ; then
nitpick: extra space. Otherwise LGTM.
```suggestion
if [ -e %{android_root}/system/core/mkbootimg/mkbootimg.py ]; then
```
With thanks.

2020-11-09 08:53 UTC, sledges approved these changes

2020-11-09 08:53 UTC, merged