Build pulseaudio-modules-droid-q for Android versions up to 10.
mer-hybris/droid-hal-device pull request #322
Opened 2022-02-18 08:09 UTC by jusa

2022-02-21 09:36 UTC, sledges requested changes
Please also rename to `-jb2q` in the commit's subject and description.

2022-02-21 13:00 UTC, jusa commented
> Please also rename to `-jb2q` in the commit's subject and description.

ah missed one place, I'll update

2022-02-22 12:04 UTC, sledges approved these changes

2022-02-22 12:20 UTC, mlehtima approved these changes

2022-02-23 08:45 UTC, merged