dhd: Immediately fail Android builds on obs if a command fails
mer-hybris/droid-hal-device pull request #323
Opened 2022-04-05 11:35 UTC by Thaodan

Run the Android build commands with set -e/errexit so that in case on
them fails the shell directly exits instead of silently continuing.

2022-04-05 13:38 UTC, sledges commented
Old `ubu-chroot` (before https://github.com/sailfishos/android-tools-hadk/pull/7) will work incorrectly on OBS when invoked with `sh -c`.
Could you provide a safe-guard check of which `ubu-chroot` is being used?

2022-04-05 15:21 UTC, sledges commented
Nitpick: typo: to -> too.

Please fall back to the old cmdline so the transition is less painful for everybody:)

2022-04-06 08:55 UTC, Thaodan commented
> Nitpick: typo: to -> too.
> 
> Please fall back to the old cmdline so the transition is less painful for everybody:)

Adjusted please review.

2022-04-06 17:07 UTC, sledges commented on droid-hal-device.inc
> +   sh="sh -c"
LGTM, worth commenting that argument parsing has been introduced together with version reporting.

2022-04-06 17:13 UTC, sledges commented
nit: obs->OBS (commit, body, and PR desc)

2022-04-06 17:15 UTC, sledges commented
in case on them fails->
in case one of them fails

2022-04-07 07:58 UTC, sledges commented
> in case on them fails-> in case one of them fails

one them -> one of them

2022-04-07 09:59 UTC, sledges requested changes
Thanks for your patience:)

2022-04-08 04:10 UTC, merged